version: "3.3"

services:

  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: vscode
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - PASSWORD=$SECRETPASSWORD
    volumes:
      - /home/docker/vscode/:/config
    labels:
      - traefik.http.routers.vscode.rule=Host(`vscode.$DOMAIN`)
      - traefik.http.routers.vscode.tls=true
      - traefik.http.routers.vscode.tls.certresolver=lets-encrypt
      - traefik.docker.network=web
      - traefik.port=8443
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - web
    restart: unless-stopped

  rtorrent:
    image: wonderfall/rtorrent-flood
    container_name: rtorrent
    restart: unless-stopped
    tty: true
    security_opt:
      - no-new-privileges:true
    ports:
      - 49184:49184
      - 49184:49184/udp
    environment:
      - UID=1000
      - GID=1000
      - FLOOD_SECRET=$SECRETPASSWORD
    volumes:
      - /home/docker/flood/:/flood-db
      - /home/media/torrents:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.rtorrent.rule=Host(`torrent.$DOMAIN`)
      - traefik.http.routers.rtorrent.tls=true
      - traefik.http.routers.rtorrent.tls.certresolver=lets-encrypt
      - traefik.docker.network=web
      - traefik.port=3000
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - web

networks:
  web:
    external: true
    name: web