[http.middlewares.simpleAuth.basicAuth]
  users = [
    "$PASSWORD"
  ]

[http.routers.api]
  rule = "Host(`monitor.$DOMAIN`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"