---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Settings

title: Kaplan VPN
background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
color: gray
base: https://MACHINEDOMAIN
favicon: /app/config/myicons/k_logo.ico

layout:
  Containers:
    style: row
    columns: 4
    
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
