[http.middlewares.simpleAuth.basicAuth]
  usersFile = ".htpassswd"

[http.routers.api]
  rule = "Host(`monitor.MACHINEDOMAIN`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"