---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Kaplan box"
subtitle: "The privacy box"
logo: "assets/icons/k_logo.png"

header: true
footer: false

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#0A161E"
    highlight-secondary: "#142C44"
    highlight-hover: "#325292"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#0A161E"
    highlight-secondary: "#142C44"
    highlight-hover: "#325292"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Privacy is key"
  icon: "fas fa-lock"
  content: "This box is intended to provide security tools. This is purely private and personal.<br>This system is powered by Docker <i class=\"fab fa-docker\"></i>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Learn docker"
    icon: "fab fa-docker"
    url: "https://docs.docker.com/get-started/overview/"
    target: "_blank" # optional html a tag target attribute

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Applications"
    icon: "fas fa-ghost"
    items:
      - name: "Portainer"
        logo: "assets/logos/portainer.png"
        subtitle: "Container management"
        tag: "management"
        url: "https://portainer.alexandre.li"
        target: "_blank" # optional html a tag target attribute
